In [23]:
import googlemaps
from pprint import pprint
import time
from datetime import datetime
import pandas as pd

gmaps = googlemaps.Client(key='AIzaSyCtuYSSDdCZ4KjpUsX3oQWpgjcNSrMpPGI')
location_name = "Restaurant"
response = gmaps.places(query=location_name,
                        location = (52.5228,13.4124),
                        radius = 100)
result = response["results"]
result

[{'business_status': 'OPERATIONAL',
  'formatted_address': 'Park Inn by Radisson, Alexanderstraße 7, 10178 Berlin, Germany',
  'geometry': {'location': {'lat': 52.5226066, 'lng': 13.4134726},
   'viewport': {'northeast': {'lat': 52.52419607989273,
     'lng': 13.41473992989272},
    'southwest': {'lat': 52.52149642010728, 'lng': 13.41204027010728}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
  'icon_background_color': '#FF9E67',
  'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
  'name': 'Restaurant Zille Stube',
  'opening_hours': {'open_now': False},
  'photos': [{'height': 3024,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102090393972559768714">OMA Ostfriesland</a>'],
    'photo_reference': 'Aap_uED2SunVpVP6eI7jbTociFmdhcGG4o6LrNNQjzhnThKhzyRRB4IyREB2gip5XftQcUl7zPpYZ1GnEj3RUiDp4gM67ufqNZYjnit31rr0GskrbM8iOtuEEhwC-8aCvQJ1PTE8XbweHGRnI-YoFL06jeC7PhHLGxCPkVSt7o2lTytL11Ze',
    'width': 4032}],
  'place_id': 'ChIJJ79c1h5OqEcRxMY1EZzptAs',
  'plus_code': {'compound_code': 'GCF7+29 Berlin',
   'global_code': '9F4MGCF7+29'},
  'rating': 4.4,
  'reference': 'ChIJJ79c1h5OqEcRxMY1EZzptAs',
  'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
  'user_ratings_total': 24},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Max-Beer-Straße 13, 10119 Berlin, Germany',
  'geometry': {'location': {'lat': 52.5255437, 'lng': 13.4079551},
   'viewport': {'northeast': {'lat': 52.52689352989272,
     'lng': 13.40930492989272},
    'southwest': {'lat': 52.52419387010728, 'lng': 13.40660527010728}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
  'icon_background_color': '#FF9E67',
  'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
  'name': 'Shiori',
  'opening_hours': {'open_now': False},
  'photos': [{'height': 3648,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104417098010160379781">Danielle Schickendantz</a>'],
    'photo_reference': 'Aap_uEBiEd0x59KUnKXtwLNgKbToDD0cmJhCSXYbKI3g9TgsEdwqMxsrUWlIde6WVVT87IY6nFjCj3mhh3WJLXGa5JxUJdNTDa7UYMiOMrNapWFfRJwmuVIrrJXZI4NY3qt7S67brKk_sTsoH9upaH7UkfF9esvGBkfuHeQXUYsCqMmq3NxO',
    'width': 2736}],
  'place_id': 'ChIJ2-sM7-FRqEcR6C4-xVX-4Gg',
  'plus_code': {'compound_code': 'GCG5+65 Berlin',
   'global_code': '9F4MGCG5+65'},
  'price_level': 3,
  'rating': 4.9,
  'reference': 'ChIJ2-sM7-FRqEcR6C4-xVX-4Gg',
  'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
  'user_ratings_total': 291},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Rosa-Luxemburg-Straße 9-11, 10178 Berlin, Germany',
  'geometry': {'location': {'lat': 52.524406, 'lng': 13.4097088},
   'viewport': {'northeast': {'lat': 52.52559357989272,
     'lng': 13.41096067989272},
    'southwest': {'lat': 52.52289392010728, 'lng': 13.40826102010728}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
  'icon_background_color': '#FF9E67',
  'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
  'name': 'Prince',
  'opening_hours': {'open_now': True},
  'photos': [{'height': 2268,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116552856185511504128">Arne Peters</a>'],
    'photo_reference': 'Aap_uECrtcQIc2NZ3I2ryZcZoQ9T1MJHEjzbFHkp1JJ5TlJ1Adr54kdGdR8Vf8AKKPXlUHoJ11XYO7-fNxuf3d6jJz8zBKK4SxlqySH-vun4VDn99bl_LC6crxOswzWUj8scigkqa27fPOeLEe1DWXv75our6m6GdlrYcuV5aTAEqljtF-Ad',
    'width': 4032}],
  'place_id': 'ChIJXfULMB5OqEcRUImSSuvv6iw',
  'plus_code': {'compound_code': 'GCF5+QV Berlin',
   'global_code': '9F4MGCF5+QV'},
  'price_level': 2,
  'rating': 4.3,
  'reference': 'ChIJXfULMB5OqEcRUImSSuvv6iw',
  'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
  'user_ratings_total': 780},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Alexanderpl. 7, 10178 Berlin, Germany',
  'geometry': {'location': {'lat': 52.5229645, 'lng': 13.4129963},
   'viewport': {'northeast': {'lat': 52.52441722989273,
     'lng': 13.41449092989272},
    'southwest': {'lat': 52.52171757010728, 'lng': 13.41179127010728}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
  'icon_background_color': '#FF9E67',
  'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
  'name': 'Spagos Restaurant - Bar & Lounge',
  'opening_hours': {'open_now': True},
  'photos': [{'height': 3024,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108969346411809026872">Pahlass Mascha</a>'],
    'photo_reference': 'Aap_uEB8Jt0wBQ7X2SstunUPn4iW-eUcYioyO3L20mMiFSZbiZt42yVjJEHsz4cH0qncuStl-9Rm1U82Y938ZXmb8v0v2UOde7REWXbYzuOJATaGex-URyRW51ybVpAmJPxav4Z525wmoriL8h-kyCawtPc7IwJzkhJOBwSM3eALC2-Axatx',
    'width': 4032}],
  'place_id': 'ChIJY-gL4x5OqEcRqYgMXh7amoU',
  'plus_code': {'compound_code': 'GCF7+55 Berlin',
   'global_code': '9F4MGCF7+55'},
  'price_level': 3,
  'rating': 3.8,
  'reference': 'ChIJY-gL4x5OqEcRqYgMXh7amoU',
  'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
  'user_ratings_total': 151},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Memhardstraße 3, 10178 Berlin, Germany',
  'geometry': {'location': {'lat': 52.52368, 'lng': 13.41031},
   'viewport': {'northeast': {'lat': 52.52516287989272,
     'lng': 13.41161827989272},
    'southwest': {'lat': 52.52246322010728, 'lng': 13.40891862010728}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
  'icon_background_color': '#FF9E67',
  'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
  'name': "L'Osteria Berlin Memhardstraße",
  'opening_hours': {'open_now': True},
  'photos': [{'height': 1960,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106752391962534506688">A Google User</a>'],
    'photo_reference': 'Aap_uECDI28XKOJvgUlyGx7Zz9rXFkcEqjcYbXxRaarkSpX-wgQA0_XZQrvw-Q8XCB17FVg_qYkMFaFSieYPO45riMmL13kZMINNZZ_rt2NEIws_nWBkhAsI-3btxELu1P1uLZE_s0UXQRogY3gOvIrvtF0_XN15_Ji5838qxRb_9GzWk2W7',
    'width': 4032}],
  'place_id': 'ChIJTc1KSh5OqEcRdYUVZlCTfGw',
  'plus_code': {'compound_code': 'GCF6+F4 Berlin',
   'global_code': '9F4MGCF6+F4'},
  'price_level': 2,
  'rating': 4.2,
  'reference': 'ChIJTc1KSh5OqEcRdYUVZlCTfGw',
  'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
  'user_ratings_total': 2350},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Rosa-Luxemburg-Straße 20, 10178 Berlin, Germany',
  'geometry': {'location': {'lat': 52.5251283, 'lng': 13.4107265},
   'viewport': {'northeast': {'lat': 52.52655867989272,
     'lng': 13.41202052989272},
    'southwest': {'lat': 52.52385902010727, 'lng': 13.40932087010728}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
  'icon_background_color': '#FF9E67',
  'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
  'name': 'Pho Co Restaurant',
  'opening_hours': {'open_now': True},
  'photos': [{'height': 2268,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102990153266108492118">Flavia Cioanca</a>'],
    'photo_reference': 'Aap_uEBCMJQ6Pq5dgAbKCDz8sTY2wdz56Q4ckihXRRi9LWgHdoFseow8DPjxrt_I2ZogdOimQjGsyt3Qx4CvqWmw-HXKViOnwzCwIRJMbMPWXup1YhKSbTZEYVuiXfWDLNE8MpafCRPSyBwW7ciqErUwy6KRK98cqiKQ8q4H1NGLbQgZ650F',
    'width': 4032}],
  'place_id': 'ChIJEa-zKdEjZUERjBNKJCvhbCc',
  'plus_code': {'compound_code': 'GCG6+37 Berlin',
   'global_code': '9F4MGCG6+37'},
  'price_level': 1,
  'rating': 4.4,
  'reference': 'ChIJEa-zKdEjZUERjBNKJCvhbCc',
  'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
  'user_ratings_total': 726},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Alexanderplatz, Panoramastraße 1A, 10178 Berlin, Germany',
  'geometry': {'location': {'lat': 52.5208204, 'lng': 13.4093677},
   'viewport': {'northeast': {'lat': 52.52237437989272,
     'lng': 13.41067857989272},
    'southwest': {'lat': 52.51967472010728, 'lng': 13.40797892010728}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
  'icon_background_color': '#FF9E67',
  'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
  'name': 'Dreh-Restaurant Sphere im Berliner Fernsehturm',
  'opening_hours': {'open_now': True},
  'photos': [{'height': 3096,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106315999020986554256">Stephan Damm</a>'],
    'photo_reference': 'Aap_uEA7Ol2ClqzfFMUnH8jbQc4oQAEwx4bsmw73Ml81RCydTRae1nZJ2zYd0ujeJg1HBKtmYGBnUXO49oWhL9onmSy48Q0-ABc9FTxstDE3NM0eB4hTHLexMqsQJOzxMWCp_HMitEfYluw20Y3iW5zRXcNPXagO3rEReLvmTy-fualkb4jx',
    'width': 5504}],
  'place_id': 'ChIJZ4w__M8jZUERE7WaomeuxqU',
  'plus_code': {'compound_code': 'GCC5+8P Berlin',
   'global_code': '9F4MGCC5+8P'},
  'price_level': 3,
  'rating': 4.4,
  'reference': 'ChIJZ4w__M8jZUERE7WaomeuxqU',
  'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
  'user_ratings_total': 3721},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Almstadtstraße 9-11, 10119 Berlin, Germany',
  'geometry': {'location': {'lat': 52.52488, 'lng': 13.40894},
   'viewport': {'northeast': {'lat': 52.52620607989272,
     'lng': 13.41039777989272},
    'southwest': {'lat': 52.52350642010727, 'lng': 13.40769812010728}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
  'icon_background_color': '#FF9E67',
  'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
  'name': 'The Klub Kitchen',
  'opening_hours': {'open_now': True},
  'photos': [{'height': 2448,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/103664405807929849961">Alexander Hartung</a>'],
    'photo_reference': 'Aap_uECAF0fdtxvHQ1il7jDWqzSV9Th5oIg4bSarGIvcVImoW3jQlyVQdDnn8Lr-f23oh0dPNxofCR2q33_uuNuq0PAyPpv-T-wOHij2caymi9cJspQVPF3FpjCPDo29BE47DNIjD07rigJw4Uod-CP-2k1ibctLItVSgt6RVYsSah5GxW0e',
    'width': 3264}],
  'place_id': 'ChIJjeJqxeNRqEcREGRrMbgzU3o',
  'plus_code': {'compound_code': 'GCF5+XH Berlin',
   'global_code': '9F4MGCF5+XH'},
  'price_level': 2,
  'rating': 4.6,
  'reference': 'ChIJjeJqxeNRqEcREGRrMbgzU3o',
  'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
  'user_ratings_total': 603},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Alexanderpl. 9, 10178 Berlin, Germany',
  'geometry': {'location': {'lat': 52.5224589, 'lng': 13.4115525},
   'viewport': {'northeast': {'lat': 52.52417397989272,
     'lng': 13.41286627989272},
    'southwest': {'lat': 52.52147432010728, 'lng': 13.41016662010728}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
  'icon_background_color': '#FF9E67',
  'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
  'name': 'Galeria Restaurant',
  'opening_hours': {'open_now': True},
  'photos': [{'height': 1536,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113178109888659753330">Good Earth</a>'],
    'photo_reference': 'Aap_uECQnyCdXZm9dOuY7ReZDqt74M82uhGIybjMugFN67uEghhyvBNuCYJgNit69xbeQNrJAxoRo0krBO49RquAVsvCW_n45p1tMxAL1f7t2JaBUew4gvoAyL9WX3wS6IDObTNoB8ecMY0uyd1d8xSOtNglp2xs8dA2AUqa3V0WDXxlVACo',
    'width': 2048}],
  'place_id': 'ChIJufv7Bx9OqEcRUt89wvklwQ8',
  'plus_code': {'compound_code': 'GCC6+XJ Berlin',
   'global_code': '9F4MGCC6+XJ'},
  'price_level': 2,
  'rating': 3.9,
  'reference': 'ChIJufv7Bx9OqEcRUt89wvklwQ8',
  'types': ['restaurant',
   'cafe',
   'food',
   'point_of_interest',
   'establishment'],
  'user_ratings_total': 501},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Panoramastraße 1A, 10178 Berlin, Germany',
  'geometry': {'location': {'lat': 52.52120919999999, 'lng': 13.4096701},
   'viewport': {'northeast': {'lat': 52.52279067989272,
     'lng': 13.41130697989272},
    'southwest': {'lat': 52.52009102010727, 'lng': 13.40860732010728}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
  'icon_background_color': '#FF9E67',
  'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
  'name': 'momotaro tavern',
  'opening_hours': {'open_now': True},
  'photos': [{'height': 4032,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108715935130673638473">A Google User</a>'],
    'photo_reference': 'Aap_uEAl-zA-FlHc_ZLrtdQGFksKB-e-F5VVfaPq6cEpAIgP2OVpU0GGQ_H5-LJNDH3NX4VQBeYNVmIBXAvqfPzNRV7z4LppRQqWoa6qhLED14-Wkz9bId1cGQxSwaNjxZxbJlxqI0Hr0MqI4UAXN1LqnJWhfW_N8A81biZsJ0Ly0jV0Mr2Q',
    'width': 3024}],
  'place_id': 'ChIJdTjciR9OqEcRNEBIOzFxVcY',
  'plus_code': {'compound_code': 'GCC5+FV Berlin',
   'global_code': '9F4MGCC5+FV'},
  'price_level': 2,
  'rating': 4.5,
  'reference': 'ChIJdTjciR9OqEcRNEBIOzFxVcY',
  'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
  'user_ratings_total': 2349},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Rosa-Luxemburg-Straße 7, 10178 Berlin, Germany',
  'geometry': {'location': {'lat': 52.5238317, 'lng': 13.4091834},
   'viewport': {'northeast': {'lat': 52.52514017989272,
     'lng': 13.41067362989272},
    'southwest': {'lat': 52.52244052010728, 'lng': 13.40797397010727}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
  'icon_background_color': '#FF9E67',
  'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
  'name': 'Dolores Mitte',
  'opening_hours': {'open_now': True},
  'photos': [{'height': 2976,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107931182522189226247">Janne Vanhemmens</a>'],
    'photo_reference': 'Aap_uEBuICc6YetQfmwpoXWDfA761ZRTVw4Tz-LqPkSEX5RNmRTILm4ZRCoEbkriW6gX0tA-B_1KdsFfYppwiFYOS4h8q0qmOzCCEn6zyTfkcd-QnhcWT6PXBL79MAl8zyPHH1eK3Q8sOFvWcrvpYB9DL0hFYKpKzXmt5kiDXl14o1kQ2qrq',
    'width': 3968}],
  'place_id': 'ChIJ9doHMh5OqEcRpBuTy_JIHzY',
  'plus_code': {'compound_code': 'GCF5+GM Berlin',
   'global_code': '9F4MGCF5+GM'},
  'price_level': 1,
  'rating': 4.4,
  'reference': 'ChIJ9doHMh5OqEcRpBuTy_JIHzY',
  'types': ['meal_takeaway',
   'restaurant',
   'food',
   'point_of_interest',
   'establishment'],
  'user_ratings_total': 4039},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Karl-Liebknecht-Str. 30, 10178 Berlin, Germany',
  'geometry': {'location': {'lat': 52.5245624, 'lng': 13.4138463},
   'viewport': {'northeast': {'lat': 52.52591222989273,
     'lng': 13.41519612989272},
    'southwest': {'lat': 52.52321257010728, 'lng': 13.41249647010728}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
  'icon_background_color': '#FF9E67',
  'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
  'name': 'Hofbräu Wirtshaus Berlin',
  'opening_hours': {'open_now': True},
  'photos': [{'height': 3000,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/103720193107624917835">Hofbräu Berlin</a>'],
    'photo_reference': 'Aap_uEBghfI5wWcJx68cHCMDgAXHXcCC0A3ZeBDx9Q0mEncAx9rIC_P-IIV0PFjU1EC-g4_jcTOzv5_hg-Fw2xaCLMxl7h_U022o145Jh52njYI4BVgyzMuljb0bBWdhLjJpeHGaxkgWQ79uCUVXQq7D_E-m6KetfA8Sn7Z8jJwXFXPAnaW6',
    'width': 2000}],
  'place_id': 'ChIJA3tAkR5OqEcRHQ3BP-tASds',
  'plus_code': {'compound_code': 'GCF7+RG Berlin',
   'global_code': '9F4MGCF7+RG'},
  'price_level': 2,
  'rating': 4.2,
  'reference': 'ChIJA3tAkR5OqEcRHQ3BP-tASds',
  'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
  'user_ratings_total': 16601},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Rochstraße 2, 10178 Berlin, Germany',
  'geometry': {'location': {'lat': 52.5242336, 'lng': 13.4073825},
   'viewport': {'northeast': {'lat': 52.52554427989273,
     'lng': 13.40887647989272},
    'southwest': {'lat': 52.52284462010729, 'lng': 13.40617682010728}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
  'icon_background_color': '#FF9E67',
  'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
  'name': 'Lebensmittel in Mitte',
  'opening_hours': {'open_now': False},
  'photos': [{'height': 3024,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107761412841811120141">Robert Dahlström</a>'],
    'photo_reference': 'Aap_uEBWr8aGIx2WiTjzyVYRjA1eEFQrDgs4x2U_5LCnMku7wM1WndSPiynLh4lQpEF8sdQRRSL0RCI7O_HjW8WAqOy_lYs6Do_3vG3JX4nfAKRLDV77QqcKLapJp34qI3Ue42wCXXgSxjxrl0HgzrK_BPPZj9Zvy0cGIcV0JmcaPK69m_gt',
    'width': 4032}],
  'place_id': 'ChIJpWJLzuFRqEcRFksSXIRbLIE',
  'plus_code': {'compound_code': 'GCF4+MX Berlin',
   'global_code': '9F4MGCF4+MX'},
  'price_level': 2,
  'rating': 4.2,
  'reference': 'ChIJpWJLzuFRqEcRFksSXIRbLIE',
  'types': ['grocery_or_supermarket',
   'restaurant',
   'food',
   'point_of_interest',
   'store',
   'establishment'],
  'user_ratings_total': 807},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Rosa-Luxemburg-Straße 30, 10178 Berlin, Germany',
  'geometry': {'location': {'lat': 52.5260438, 'lng': 13.4114422},
   'viewport': {'northeast': {'lat': 52.52740477989272,
     'lng': 13.41267202989272},
    'southwest': {'lat': 52.52470512010727, 'lng': 13.40997237010728}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
  'icon_background_color': '#FF9E67',
  'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
  'name': 'SOY',
  'opening_hours': {'open_now': True},
  'photos': [{'height': 2099,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107643431123523337578">Alexandrina Hadzhiyska</a>'],
    'photo_reference': 'Aap_uECEBN_3f2qClJeTL7jXRL1Js1UISxztunZR_1fDFvUNwvqs3webYw8TbWvlYUveLxSTZmz-mbjb7tcnqJGWreO5PZhPsIDMipce2FnGbQzni4rRmjO1d-b7Fc81QlPJLQmkOD5WvivF78say08XNk2Nz4EQ4o-tFdEftV2OHNwrvYbs',
    'width': 2400}],
  'place_id': 'ChIJbX7JCh5OqEcRQbUaQ-aMoFA',
  'plus_code': {'compound_code': 'GCG6+CH Berlin',
   'global_code': '9F4MGCG6+CH'},
  'price_level': 2,
  'rating': 4.4,
  'reference': 'ChIJbX7JCh5OqEcRQbUaQ-aMoFA',
  'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
  'user_ratings_total': 1702},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Alexanderpl. 7, 10178 Berlin, Germany',
  'geometry': {'location': {'lat': 52.5226699, 'lng': 13.4136219},
   'viewport': {'northeast': {'lat': 52.52423357989273,
     'lng': 13.41480112989272},
    'southwest': {'lat': 52.52153392010728, 'lng': 13.41210147010728}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
  'icon_background_color': '#FF9E67',
  'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
  'name': "Humbolt's Restaurant",
  'opening_hours': {'open_now': False},
  'photos': [{'height': 2976,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110813973753497780189">Alexander Eichholtz</a>'],
    'photo_reference': 'Aap_uEBUDvjY6APd5hPF5SLhZa1TaalD7B7DUutZIK9oRzAIYh9dKY3Bfi4gxI94_y1QucCKug82XKvoMyZsNGIKDP_pe9iVepZjB63zPk0kI5NZlkijzOaYkXC6umoFTTYRH1qLFZ1SXMLp43iOMqFIT6Ab_qxNbWa89t8HLtR86Nackz05',
    'width': 3968}],
  'place_id': 'ChIJyy4mIh9OqEcRP1hu2zIMaUQ',
  'plus_code': {'compound_code': 'GCF7+3C Berlin',
   'global_code': '9F4MGCF7+3C'},
  'rating': 3.5,
  'reference': 'ChIJyy4mIh9OqEcRP1hu2zIMaUQ',
  'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
  'user_ratings_total': 19},

In [89]:
result[0]['name']

'Restaurant Zille Stube'

In [74]:
df = pd.DataFrame.from_dict(result)

In [75]:
df = df.drop(['business_status','opening_hours','types','icon','icon_background_color','icon_mask_base_uri', 'photos', 'place_id', 'plus_code', 'reference'], axis = 1)

In [77]:
lat = []
lon = []

for items in result:
    lat.append(items['geometry']['location']['lat'])
    lon.append(items['geometry']['location']['lng'])
    
df['lat'] = lat
df['lon'] = lon

df = df.drop(['geometry'], axis = 1)

In [78]:
df.head()

,formatted_address,name,rating,user_ratings_total,price_level,permanently_closed,lat,lon
0,"Park Inn by Radisson, Alexanderstraße 7, 10178...",Restaurant Zille Stube,4.4,24,NaN,NaN,52.522607,13.413473
1,"Max-Beer-Straße 13, 10119 Berlin, Germany",Shiori,4.9,291,3.0,NaN,52.525544,13.407955
2,"Rosa-Luxemburg-Straße 9-11, 10178 Berlin, Germany",Prince,4.3,780,2.0,NaN,52.524406,13.409709
3,"Alexanderpl. 7, 10178 Berlin, Germany",Spagos Restaurant - Bar & Lounge,3.8,151,3.0,NaN,52.522965,13.412996
4,"Memhardstraße 3, 10178 Berlin, Germany",L'Osteria Berlin Memhardstraße,4.2,2350,2.0,NaN,52.523680,13.410310

In [135]:
lst_ = []


for item in result:
    name_ = item['name']
    lst_.append(name_.split())

#for restaurants_names in :
      #  lst_.append(restaurants_names)
lst_

[['Restaurant', 'Zille', 'Stube'],
 ['Shiori'],
 ['Prince'],
 ['Spagos', 'Restaurant', '-', 'Bar', '&', 'Lounge'],
 ["L'Osteria", 'Berlin', 'Memhardstraße'],
 ['Pho', 'Co', 'Restaurant'],
 ['Dreh-Restaurant', 'Sphere', 'im', 'Berliner', 'Fernsehturm'],
 ['The', 'Klub', 'Kitchen'],
 ['Galeria', 'Restaurant'],
 ['momotaro', 'tavern'],
 ['Dolores', 'Mitte'],
 ['Hofbräu', 'Wirtshaus', 'Berlin'],
 ['Lebensmittel', 'in', 'Mitte'],
 ['SOY'],
 ["Humbolt's", 'Restaurant'],
 ['The', 'Grand'],
 ['Madami', '-', "Mom's", 'vietnamese', 'kitchen'],
 ['Restaurant', 'Wandel'],
 ["Schlögl's", '-', 'Altberliner', 'Gaststätte'],
 ['Bibi', 'Mix']]

In [138]:
# remove 'restaurant, bar, lounge' from restaurant name

to_remove = ['Restaurant', 'Bar', 'Lounge']

for items in lst_:
    for word in items:
        for toremove in to_remove:
            if word == toremove:
                items.remove(word)

clean_lst = []

for items in lst_:
    if '-' in items:
        index = items.index('-') 
        clean_lst.append(items[:index])
    else:
        clean_lst.append(items)
        
# cut out anything that comes after a '-' in a restaurant name
        
clean_name = ''
name_lst = []

for item in clean_lst:
    for word in item:
        clean_name += word +' '
    name_lst.append(clean_name.rstrip())
    clean_name = ''

In [165]:
# add cleaned restaurant names to the df

df['name'] = name_lst

In [167]:
df

,formatted_address,name,rating,user_ratings_total,price_level,permanently_closed,lat,lon
0,"Park Inn by Radisson, Alexanderstraße 7, 10178...",Zille Stube,4.4,24,NaN,NaN,52.522607,13.413473
1,"Max-Beer-Straße 13, 10119 Berlin, Germany",Shiori,4.9,291,3.0,NaN,52.525544,13.407955
2,"Rosa-Luxemburg-Straße 9-11, 10178 Berlin, Germany",Prince,4.3,780,2.0,NaN,52.524406,13.409709
3,"Alexanderpl. 7, 10178 Berlin, Germany",Spagos,3.8,151,3.0,NaN,52.522965,13.412996
4,"Memhardstraße 3, 10178 Berlin, Germany",L'Osteria Berlin Memhardstraße,4.2,2350,2.0,NaN,52.523680,13.410310
5,"Rosa-Luxemburg-Straße 20, 10178 Berlin, Germany",Pho Co,4.4,726,1.0,NaN,52.525128,13.410727
6,"Alexanderplatz, Panoramastraße 1A, 10178 Berli...",Dreh-Restaurant Sphere im Berliner Fernsehturm,4.4,3721,3.0,NaN,52.520820,13.409368
7,"Almstadtstraße 9-11, 10119 Berlin, Germany",The Klub Kitchen,4.6,603,2.0,NaN,52.524880,13.408940
8,"Alexanderpl. 9, 10178 Berlin, Germany",Galeria,3.9,501,2.0,NaN,52.522459,13.411553
9,"Panoramastraße 1A, 10178 Berlin, Germany",momotaro tavern,4.5,2349,2.0,NaN,52.521209,13.409670
10,"Rosa-Luxemburg-Straße 7, 10178 Berlin, Germany",Dolores Mitte,4.4,4039,1.0,NaN,52.523832,13.409183
11,"Karl-Liebknecht-Str. 30, 10178 Berlin, Germany",Hofbräu Wirtshaus Berlin,4.2,16601,2.0,NaN,52.524562,13.413846
12,"Rochstraße 2, 10178 Berlin, Germany",Lebensmittel in Mitte,4.2,807,2.0,NaN,52.524234,13.407383
13,"Rosa-Luxemburg-Straße 30, 10178 Berlin, Germany",SOY,4.4,1702,2.0,NaN,52.526044,13.411442
14,"Alexanderpl. 7, 10178 Berlin, Germany",Humbolt's,3.5,19,NaN,NaN,52.522670,13.413622
15,"Hirtenstraße 4, 10178 Berlin, Germany",The Grand,4.1,890,3.0,True,52.525520,13.412579
16,"Rosa-Luxemburg-Straße 3, 10178 Berlin, Germany",Madami,4.4,2693,2.0,NaN,52.523365,13.408945
17,"Bernhard-Weiß-Straße 6, 10178 Berlin, Germany",Wandel,4.1,505,1.0,NaN,52.524076,13.416781
18,"Karl-Liebknecht-Str. 9, 10178 Berlin, Germany",Schlögl's,4.4,911,2.0,NaN,52.521300,13.406281
19,"Rosa-Luxemburg-Straße 5-7, 10178 Berlin, Germany",Bibi Mix,4.1,152,2.0,NaN,52.523666,13.409089