## API REQUEST

In [1]:
import requests
import pandas as pd

In [2]:
def fetch_here(lat, lon, api_key):
    
    url = f'https://discover.search.hereapi.com/v1/discover?at={lat},{lon}&q=restaurant&limit=100&apiKey={api_key}'
    response = requests.get(url)
    
    if response.status_code != 200:
        return ''
    data = response.json()
    
    return data['items']

## Call API on 10km around the center of Berlin

 Generate coordinates list

In [3]:
# generate a list of coordinates within 10 km around the center of Berlin

list_coordinates_with_distance = pd.read_csv('/Users/support/code/ClaireLa/next_restaurant/coordinates_list/Berlin_coordinates_with_distances.csv')

list_coordinates_with_distance = list_coordinates_with_distance.reset_index()
ten_k = list_coordinates_with_distance[list_coordinates_with_distance['distance'] < 10]
ten_k.sort_values(by = 'distance')

         index        lat        lng  distance
78958    78958  52.525779  13.400227         0
83447    83447  52.515861  13.418049         0
79692    79692  52.511352  13.403197         0
81201    81201  52.519467  13.409138         0
81200    81200  52.518566  13.409138         0
...        ...        ...        ...       ...
77925    77925  52.608731  13.395771         9
77924    77924  52.607830  13.395771         9
77923    77923  52.606928  13.395771         9
78292    78292  52.601518  13.397257         9
117213  117213  52.530287  13.551712         9

[31190 rows x 4 columns]

In [ ]:
# Save list into csv file

ten_k.to_csv(f'/Users/support/code/ClaireLa/next_restaurant/coordinates_list/ten_kilometers.csv')

In [10]:
ten_k.tail()

         index        lat        lng  distance
117209  117209  52.526681  13.551712         9
117210  117210  52.527582  13.551712         9
117211  117211  52.528484  13.551712         9
117212  117212  52.529386  13.551712         9
117213  117213  52.530287  13.551712         9

Call the API

In [11]:
# Call the API


for i in range(14462, len(ten_k)):
    
    query = fetch_here(ten_k.lat.iloc[i],
                       ten_k.lng.iloc[i],
                       'e8Jr90z14vvM6WedTBedm2Trnv4J_-KLqH4vVllGqqI')
    
    # put in a df
    
    dataframe = pd.DataFrame.from_dict(query)

    
    # get index
    
    index = ten_k.iloc[i]['index']
    
    # Save into csv file
    
    dataframe.to_csv(f'/Users/support/code/ClaireLa/next_restaurant/here_query_ten_k/here_query_{index}.csv')

    
    
# I stopped at 28028

KeyboardInterrupt:

Concatenate CSV files

In [13]:
# concatenate CSV files 

import glob
import pandas as pd

df = pd.concat(map(pd.read_csv, glob.glob('../here_query_ten_k/*.csv')))

Drop duplicates

In [14]:
df.shape

(2806800, 15)

In [16]:
df.to_csv(f'/Users/support/code/ClaireLa/next_restaurant/here_query_ten_k/big_table.csv')

In [20]:
big_table = pd.read_csv('/Users/support/code/ClaireLa/next_restaurant/here_query_ten_k/big_table.csv')

In [21]:
big_table.head()

,Unnamed: 0,Unnamed: 0.1,title,id,ontologyId,resultType,address,position,access,distance,categories,references,foodTypes,contacts,openingHours,chains
0,0,0,Schrödingers,here:pds:place:2768lxx5-31745b00bb500fb9d1b8f6...,here:cm:ontology:restaurant,place,"{'label': 'Schrödingers, Helmholtzstraße 23, 1...","{'lat': 52.52209, 'lng': 13.32699}","[{'lat': 52.52196, 'lng': 13.32705}]",113,"[{'id': '100-1000-0000', 'name': 'Restaurant',...","[{'supplier': {'id': 'yelp'}, 'id': 'Jn7APqtDL...","[{'id': '302-000', 'name': 'Deutsch', 'primary...","[{'phone': [{'value': '+491603485538'}], 'www'...","[{'categories': [{'id': '100-1000-0000'}], 'te...",NaN
1,1,1,Esa Noa,here:pds:place:276u336z-e84b2da1e9ed4dd1afa848...,here:cm:ontology:restaurant,place,"{'label': 'Esa Noa, Helmholtzstraße 24, 10587 ...","{'lat': 52.52204, 'lng': 13.32672}","[{'lat': 52.52191, 'lng': 13.32678}]",125,"[{'id': '100-1000-0000', 'name': 'Restaurant',...","[{'supplier': {'id': 'tripadvisor'}, 'id': '14...","[{'id': '301-000', 'name': 'Französisch', 'pri...","[{'phone': [{'value': '+493049958347'}], 'www'...",NaN,NaN
2,2,2,Rosso,here:pds:place:276u336z-645452bc5ceb4d0ca1f535...,here:cm:ontology:restaurant,place,"{'label': 'Rosso, Helmholtzstraße 24, 10587 Be...","{'lat': 52.52204, 'lng': 13.32672}","[{'lat': 52.52191, 'lng': 13.32678}]",125,"[{'id': '100-1000-0000', 'name': 'Restaurant',...","[{'supplier': {'id': 'tripadvisor'}, 'id': '12...","[{'id': '800-057', 'name': 'Pizza', 'primary':...","[{'phone': [{'value': '+493058848011'}], 'www'...","[{'categories': [{'id': '100-1000-0000'}, {'id...","[{'id': '2606', 'name': 'Rosso'}]"
3,3,3,Restaurant Garamond,here:pds:place:276u336z-018dd7dd1f304eedbb9848...,here:cm:ontology:restaurant,place,"{'label': 'Restaurant Garamond, Gotzkowskystra...","{'lat': 52.52336, 'lng': 13.32932}","[{'lat': 52.52334, 'lng': 13.32959}]",131,"[{'id': '100-1000-0000', 'name': 'Restaurant',...","[{'supplier': {'id': 'core'}, 'id': '101032604...","[{'id': '302-000', 'name': 'Deutsch', 'primary...","[{'phone': [{'value': '+49307478200'}, {'value...","[{'text': ['Mon: 12:30 - 14:30, 18:00 - 22:00'...",NaN
4,4,4,La Fabrica Food,here:pds:place:276u336z-fb7ebcb1328c4ab9a6df4b...,here:cm:ontology:restaurant,place,"{'label': 'La Fabrica Food, Gotzkowskystraße, ...","{'lat': 52.52358, 'lng': 13.32941}","[{'lat': 52.52357, 'lng': 13.32962}]",144,"[{'id': '100-1000-0000', 'name': 'Restaurant',...","[{'supplier': {'id': 'yelp'}, 'id': 'NdXd7NcZj...","[{'id': '800-064', 'name': 'International', 'p...",[{'phone': [{'value': '+493036751982'}]}],"[{'text': ['Tue-Sun: 09:00 - 22:00'], 'isOpen'...",NaN

In [ ]:
df.drop_duplicates(subset = 'title', inplace = True)

## DATA CLEANING

Delete useless columns

In [ ]:

dataframe_ = df.drop(['id','ontologyId','resultType', 'references', 'access','categories'], axis=1)

Reshape content

In [ ]:
lat = []
lon = []
full_address = []
district = []
street = []
house_nr = []
zip_code = []
cuisine_general = []
cuisine_detail = []
opening_hours = []

    # Clean the data

    for restaurant in query:
        for item in to_delete_1:
            del restaurant['address'][item]
            
    dataframe = pd.DataFrame.from_dict(query)
    dataframe_ = dataframe.drop(['id','ontologyId','resultType', 'references', 'contacts', 'access','categories'], axis=1)

    # separate lat and lon
    
    for items in query:
        lat.append(items['position']['lat'])
        lon.append(items['position']['lng'])
    
    dataframe_['lat'] = lat
    dataframe_['lon'] = lon
    dataframe_.drop(['position'], axis = 1)
    
    # separate full address

    for items in query:
        full_address.append(items['address']['label'])
        district.append(items['address']['district'])

    dataframe_['full_address'] = full_address 
    dataframe_['district'] = district
    
    # separate street name

    for items in query:
        try:
            street.append(items['address']['street'])
        except:
            street.append('NaN')

    dataframe_['street'] = street
    
    
    # separate house number

    for items in query:
        try:
            house_nr.append(items['address']['houseNumber'])
        except:
            house_nr.append('NaN')

    dataframe_['house_nr'] = house_nr
    
    # separate zipcode

    for items in query:
        try:
            zip_code.append(items['address']['postalCode'])
        except:
            zip_code.append('NaN')


    dataframe_['zip_code'] = zip_code
    
    
    # get food types

    for items in query:
        try:
            cuisine_general.append(items['foodTypes'][0]['name'])
        except:
            cuisine_general.append('NaN')

    dataframe_['cuisine_general'] = cuisine_general
    
    # get food types detail

    for items in query:
        try:
            cuisine_detail.append(items['foodTypes'][1]['name'])
        except:
            cuisine_detail.append('NaN')

    dataframe_['cuisine_detail'] = cuisine_detail
    
    # get opening hours

    for items in query:
        try:
            opening_hours.append(items['openingHours'][0]['text'][0])
        except:
            opening_hours.append('NaN')

    dataframe_['opening_hours'] = opening_hours
    
    # drop useless columns

    final_dataframe = dataframe_.drop(['foodTypes','position','address','openingHours'],axis = 1)

    # rename the restaurant name
    
    final_dataframe = final_dataframe.rename(columns={"title": 'restaurant_name'})
    
    # Save into csv file
    
    final_dataframe.to_csv(f'/Users/support/code/ClaireLa/next_restaurant/here_query{_index}.csv')

## INSPECT THE DATASET

Count null values

In [ ]:
# null counts

final_df['cuisine_general'].value_counts()
final_df['cuisine_detail'].value_counts()

In [ ]:
final_df['restaurant_name'].unique()